version: '3.8'

services:
  task-db:
    image: mysql:8
    container_name: task-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: task_db
    ports:
      - "3316:3306"
    volumes:
      - task-data:/var/lib/mysql

  user-db:
    image: mysql:8
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: user_db
    ports:
      - "3317:3306"
    volumes:
      - user-data:/var/lib/mysql

  notification-db:
    image: mysql:8
    container_name: notification-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: notification_db
    ports:
      - "3318:3306"
    volumes:
      - notification-data:/var/lib/mysql

volumes:
  task-data:
  user-data:
  notification-data: